# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#site-configuration

baseURL = "https://blog.tomy.me/"
defaultContentLanguage = "zh-tw"
defaultContentLanguageInSubdir = true
timeZone = "Asia/Taipei"

enableRobotsTXT = true
paginate = 10
summaryLength = 0

googleAnalytics = "G-B7DGGHK2JX"

[outputs]
  home = ["HTML", "RSS", "JSON"]
