# -- Site Configuration --
# https://gohugo.io/getting-started/configuration/#all-configuration-settings
# https://jpanther.github.io/congo/docs/configuration/#site-configuration

baseURL = "https://blog.tomy.me/"
defaultContentLanguage = "zh-tw"
defaultContentLanguageInSubdir = true
timeZone = "Asia/Taipei"

enableRobotsTXT = true
paginate = 10
summaryLength = 0

googleAnalytics = "G-B7DGGHK2JX"

[Social]
  twitter = "tomy0000000"  # For twitter:site

[outputs]
  home = ["HTML", "RSS", "JSON"]
