# -- Site Configuration --
# https://gohugo.io/getting-started/configuration/#all-configuration-settings
# https://jpanther.github.io/congo/docs/configuration/#site-configuration
theme = "congo"

baseURL = "https://blog.tomy.me/"
defaultContentLanguage = "zh-tw"
defaultContentLanguageInSubdir = true
timeZone = "Asia/Taipei"

enableRobotsTXT = true
paginate = 10
summaryLength = 0

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[Social]
  twitter = "tomy0000000"  # For twitter:site

[privacy]
  [privacy.youtube]
    privacyEnhanced = true
