# -- Site Configuration --
# https://gohugo.io/getting-started/configuration/#all-configuration-settings
# https://jpanther.github.io/congo/docs/configuration/#site-configuration

buildDrafts = true

[outputs]
home = ["HTML", "RSS", "JSON"]
