#:schema https://www.schemastore.org/hugo.json
# https://gohugo.io/getting-started/configuration/#all-configuration-settings
# https://jpanther.github.io/congo/docs/configuration/#site-configuration

baseURL = "https://localhost:1313"
buildDrafts = true
